# DataSource Config
spring:
  datasource:
    driver-class-name: org.h2.Driver
    schema: classpath:db/schema-h2.sql
    data: classpath:db/data-h2.sql
    url: jdbc:h2:mem:test
    #    driver-class-name: com.mysql.jdbc.Driver
    #    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=false&?useServerPrepStmts=false&rewriteBatchedStatements=true
    username: root
    password: mysqlpwd@123

server:
  port: 10086

# Logger Config
logging:
  level:
    focus.demo: debug

# mybatis-plus Config
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: focus.editor.entity